# Generated by Django 5.0.1 on 2024-02-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='ordered_products',
        ),
    ]
