# Generated by Django 5.0.1 on 2024-02-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
