# Generated by Django 5.0.1 on 2024-02-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0003_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='products'),
        ),
    ]
