# Generated by Django 5.0.1 on 2024-02-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0005_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='or_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homework_02.order'),
        ),
    ]
