# Generated by Django 5.0.1 on 2024-02-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0006_orderedproduct_or_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='or_order',
            new_name='in_order',
        ),
    ]
