# Generated by Django 5.0.1 on 2024-02-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0008_orderedproduct_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='is_ordered',
        ),
    ]
