# Generated by Django 5.0.1 on 2024-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0009_remove_orderedproduct_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='in_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
