# Generated by Django 5.0.1 on 2024-02-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0010_remove_orderedproduct_in_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='in_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homework_02.order'),
        ),
    ]
