# Generated by Django 5.0.1 on 2024-02-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0013_alter_orderedproduct_in_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='in_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework_02.order'),
        ),
    ]
