# Generated by Django 5.0.1 on 2024-02-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0014_alter_orderedproduct_in_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='in_order',
        ),
    ]
