# Generated by Django 5.0.1 on 2024-02-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0017_alter_client_options_client_change_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-change_date'], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'ordering': ['-product__date_added'], 'verbose_name': 'заказанный товар', 'verbose_name_plural': 'заказанные товары'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_added'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_02.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_products',
            field=models.ManyToManyField(to='homework_02.orderedproduct', verbose_name='заказанные товары'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='общая сумма'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='in_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework_02.order', verbose_name='в заказе'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_02.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
    ]
