# Generated by Django 5.0.1 on 2024-02-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_02', '0018_alter_client_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='дата добавления'),
        ),
    ]
