# Generated by Django 5.0.1 on 2024-01-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('H', 'Heads'), ('T', 'Tails')], max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
