# Generated by Django 5.0.1 on 2024-02-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_02', '0005_alter_article_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set(),
        ),
    ]
