# Generated by Django 5.0.1 on 2024-02-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_02', '0006_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'article')},
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together={('author', 'article')},
        ),
    ]
