# Generated by Django 5.0.1 on 2024-02-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_02', '0011_alter_article_author_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='side',
            field=models.CharField(choices=[('H', 'Орёл'), ('T', 'Решка')], max_length=1, verbose_name='Сторона'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время броска'),
        ),
    ]
